using UnityEngine;
using System.Collections.Generic;

public enum EItemType
{
    Equip = 1,
    Rune = 2,
    Stone = 3,
    Props = 4,
    Skill = 5,
}

// Item
//  the base of all items in system.
//
//  the item is serialized from the server vs JSON.
//
//  different item type contains different attributes.
//  such as the equip even contains dynamic attributes generated by strengthen system.
//
//  so it store all of the attributes in the dictionary Attrib.
//  you can convert it to some XxxxItem for easy use through ToXxxItem() function.
//
[ProtoBuf.ProtoContract]
public class Item : ICommand
{
    // this field will be serialized form server vs json.
    [ProtoBuf.ProtoMember(1)]
    public SmartInt ID { get; set; }

    [ProtoBuf.ProtoMember(2)]
    public SmartInt Base { get; set; }

    [ProtoBuf.ProtoMember(3)]
    public SmartInt Num { get; set; }

    [ProtoBuf.ProtoMember(4)]
    public Dictionary<string, SmartInt> Attrib { get; set; }

    public Item()
    {
        Attrib = new Dictionary<string, SmartInt>();
    }

    // this is private field.
    ItemBase mItemBase = null;

    // this is public property.
    public ItemBase ItemBase { 
		get { if( Init() )
				return mItemBase; 
			  else 
				return null;
		}
	}

    // get a custom attrib with a name, default value is 0.
    public int GetAttrib(string name)
    {
        return GetAttrib(name, 0);
    }

    // get a custom attrib with a name, if attrib isn't found, default value returned.
    public int GetAttrib(string name, int defaultValue)
    {
        SmartInt ret;
        if (Attrib.TryGetValue(name, out ret))
            return ret;
        return defaultValue;
    }

    // setup a custom attrib.
    public void SetAttrib(string name, int value)
    {
        Attrib[name] = value;
    }

    // this should be called after the JSON serialize finished.
    public bool Init()
    {
        mItemBase = ItemBaseManager.Instance.GetItem(Base);
        if (mItemBase == null)
        {
            Debug.LogError("The item isnot defined in itembase: " + ID);
            return false;
        }

        return true;
    }
	
    // convert this item to [EquipItem] for easy use.
    public EquipItem ToEquipItem() { return (mItemBase.MainType == (int)EItemType.Equip) ? new EquipItem(this) : null; }

    // convert this item to [SkillItem] for easy use.
    public SkillItem ToSkillItem() { return (mItemBase.MainType == (int)EItemType.Skill) ? new SkillItem(this) : null; }

    // convert this item to [PropsItem] for easy use.
    public PropsItem ToPropsItem() { return (mItemBase.MainType == (int)EItemType.Props) ? new PropsItem(this) : null; }
}
