//Autogen by ProtoBuilder, do not edit it manualy.

public enum BaseCmd
{
    BStart = 200,
}
public enum ERequestTypes
{
    EAddFriendCmd = 0,
    EBatchSellCmd = 1,
    EBuyCmd = 2,
    EBuyPackagePageCmd = 3,
    EBuyStrengthCmd = 4,
    ECombineCmd = 5,
    ECreateUserCmd = 6,
    EDeleteFriendCmd = 7,
    EDeleteMailCmd = 8,
    EDeleteUserCmd = 9,
    EEnterGameCmd = BaseCmd.BStart + 10,
    EEnterLevelCmd = 11,
    EEquipCmd = 12,
    EEquipPropsCmd = 13,
    EFetchAttachCmd = 14,
    EFetchQuestRewardCmd = 15,
    EFinishLevelCmd = 16,
    EFinishPvpCmd = 17,
    EGetBackPackCmd = 18,
    EGetChatCmd = 19,
    EGetCityUsersCmd = 20,
    EGetFriendsCmd = 21,
    EGetMailsCmd = 22,
    EGetPveInfoCmd = 23,
    EGetPvpInfoCmd = 24,
    EGetQuestListCmd = 25,
    EGetSkillPackCmd = 26,
    EGetStrengthCmd = 27,
    EGetTopListCmd = 28,
    EGetUserAttribCmd = 29,
    EGetUserDataCmd = BaseCmd.BStart + 30,
    EJoinPvpCmd = 31,
    ELeaveGameCmd = 32,
    ELeaveLevelCmd = 33,
    ELeavePvpCmd = 34,
    ELoginCmd = BaseCmd.BStart + 35,
    EMoveCmd = BaseCmd.BStart + 36,
    EOpenCellCmd = 37,
    EReadMailCmd = 38,
    EReLoginCmd = 39,
    ERequestCmd = 40,
    EReviveCmd = 41,
    EReviveInfoCmd = 42,
    ESellCmd = 43,
    ESendChatCmd = 44,
    ESendMailCmd = 45,
    EServerTestRequest = 46,
    ESkillAddRuneCmd = 47,
    ESkillBuySlotCmd = 48,
    ESkillEquipCmd = 49,
    ESkillLearnCmd = 50,
    ESkillUpgradeCmd = 51,
    EStrengthenCmd = 52,
    EUnEquipCmd = 53,
    EUseItemCmd = 54,
    EGetLoginInfoCmd = BaseCmd.BStart + 55,
    ERechargeCmd = 56,
    ESignInCmd = 57,
    EFinishNewGuideCmd = 58,
    EExchangeCmd = 59,
    EFetchTurntableRewardCmd = 60,
    EGetTurntableDataCmd = 61,
    EMax = 62,
}
